### PR TITLE
Convenience method to setup images in the controller.

### PR DESCRIPTION
**Pull request by kikoseijo**
Now you can do something like, : and update the image on the cards and open graph.

```php
$this->seo()
          ->setTitle(trans('conectores.'.$conector_id.'.seo_title'))
          ->setImage(asset('img/conectores-aplicaciones-moviles/modulo-'.$conector_id.'.png'))
          ->setDescription(trans('conectores.'.$conector_id.'.seo_desc'));
```

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
Hi @kikoseijo, thanks for your pull request.

There are multiple changes that breaks the code style i'm using and also missing tests + unnecessary files added (`.DS_Store`).

I'm going to add this feature today with tests.

But I really appreciate your spending time with this PR 👍

**Comment by arcanedev-maroc** [comment]
Done: #27

**Comment by arcanedev-maroc** [comment]
@kikoseijo try to update the `seo-helper` to `1.3.1` and see if it works for you.

**Comment by kikoseijo** [comment]
I love it, I really do, you got nice peace of work here.
I did at 6AM after a working marathon, 

Point to me what else needs done and ill do, I don’t mind, Illl like to help.

Thanks for your reply.

**Pull request closed without merging**
